version: '2'
services:
  # PostgreSQL database
  db:
    image: mdillon/postgis:9.6
    restart: always
    environment:
      POSTGRES_DB: absinthepedia
      POSTGRES_USER: brewmaster
      POSTGRES_PASSWORD: brewmaster
    ports:
      - "5432:5432"

  # Phoenix web server
  web:
    build:
      context: .
      dockerfile: docker/phoenix/Dockerfile
    command: ./run_web.sh
    volumes:
      - .:/code
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
